<?php

/**
 * @file
 * Contains pages_test.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pages_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pages_test module.
    case 'help.page.pages_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pages Test') . '</p>';
      return $output;

    default:
  }
}
