<?php

/**
 * @file
 * Contains block_test.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function block_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_test module.
    case 'help.page.block_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal 8 blocks.') . '</p>';
      return $output;

    default:
  }
}
